-- Script de atualização de eleitores
-- Gerado automaticamente em 17/03/2026, 01:50:32
-- Fonte: TERRITÓRIOS DE IDENTIDADE BAHIA 09-2025.xlsx
--
-- Total de municípios com dados: 391
-- Total de eleitores: 10.644.461

-- ============================================
-- Atualizar população dos municípios
-- ============================================

UPDATE territorios_municipios SET populacao = 12058 WHERE UPPER(TRIM(nome_municipio)) = 'BARRA DO MENDES';
UPDATE territorios_municipios SET populacao = 11588 WHERE UPPER(TRIM(nome_municipio)) = 'BARRO ALTO';
UPDATE territorios_municipios SET populacao = 14302 WHERE UPPER(TRIM(nome_municipio)) = 'CAFARNAUM';
UPDATE territorios_municipios SET populacao = 19938 WHERE UPPER(TRIM(nome_municipio)) = 'CANARANA';
UPDATE territorios_municipios SET populacao = 13608 WHERE UPPER(TRIM(nome_municipio)) = 'CENTRAL';
UPDATE territorios_municipios SET populacao = 9703 WHERE UPPER(TRIM(nome_municipio)) = 'GENTIO DO OURO';
UPDATE territorios_municipios SET populacao = 13742 WHERE UPPER(TRIM(nome_municipio)) = 'IBIPEBA';
UPDATE territorios_municipios SET populacao = 15588 WHERE UPPER(TRIM(nome_municipio)) = 'IBITITÁ';
UPDATE territorios_municipios SET populacao = 8829 WHERE UPPER(TRIM(nome_municipio)) = 'IPUPIARA';
UPDATE territorios_municipios SET populacao = 50377 WHERE UPPER(TRIM(nome_municipio)) = 'IRECÊ';
UPDATE territorios_municipios SET populacao = 10794 WHERE UPPER(TRIM(nome_municipio)) = 'ITAGUAÇU DA BAHIA';
UPDATE territorios_municipios SET populacao = 19451 WHERE UPPER(TRIM(nome_municipio)) = 'JOÃO DOURADO';
UPDATE territorios_municipios SET populacao = 14126 WHERE UPPER(TRIM(nome_municipio)) = 'JUSSARA';
UPDATE territorios_municipios SET populacao = 21801 WHERE UPPER(TRIM(nome_municipio)) = 'LAPÃO';
UPDATE territorios_municipios SET populacao = 10852 WHERE UPPER(TRIM(nome_municipio)) = 'MULUNGU DO MORRO';
UPDATE territorios_municipios SET populacao = 12034 WHERE UPPER(TRIM(nome_municipio)) = 'PRESIDENTE DUTRA';
UPDATE territorios_municipios SET populacao = 16345 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO GABRIEL';
UPDATE territorios_municipios SET populacao = 12124 WHERE UPPER(TRIM(nome_municipio)) = 'UIBAÍ';
UPDATE territorios_municipios SET populacao = 35122 WHERE UPPER(TRIM(nome_municipio)) = 'XIQUE-XIQUE';
UPDATE territorios_municipios SET populacao = 48148 WHERE UPPER(TRIM(nome_municipio)) = 'BOM JESUS DA LAPA';
UPDATE territorios_municipios SET populacao = 9528 WHERE UPPER(TRIM(nome_municipio)) = 'BROTAS DE MACAÚBAS';
UPDATE territorios_municipios SET populacao = 22358 WHERE UPPER(TRIM(nome_municipio)) = 'CARINHANHA';
UPDATE territorios_municipios SET populacao = 5277 WHERE UPPER(TRIM(nome_municipio)) = 'FEIRA DA MATA';
UPDATE territorios_municipios SET populacao = 21166 WHERE UPPER(TRIM(nome_municipio)) = 'IBOTIRAMA';
UPDATE territorios_municipios SET populacao = 12215 WHERE UPPER(TRIM(nome_municipio)) = 'IGAPORÃ';
UPDATE territorios_municipios SET populacao = 13306 WHERE UPPER(TRIM(nome_municipio)) = 'MALHADA';
UPDATE territorios_municipios SET populacao = 9674 WHERE UPPER(TRIM(nome_municipio)) = 'MATINA';
UPDATE territorios_municipios SET populacao = 7784 WHERE UPPER(TRIM(nome_municipio)) = 'MORPARÁ';
UPDATE territorios_municipios SET populacao = 9805 WHERE UPPER(TRIM(nome_municipio)) = 'MUQUÉM DE SÃO FRANCISCO';
UPDATE territorios_municipios SET populacao = 16550 WHERE UPPER(TRIM(nome_municipio)) = 'OLIVEIRA DOS BREJINHOS';
UPDATE territorios_municipios SET populacao = 24269 WHERE UPPER(TRIM(nome_municipio)) = 'PARATINGA';
UPDATE territorios_municipios SET populacao = 23672 WHERE UPPER(TRIM(nome_municipio)) = 'RIACHO DE SANTANA';
UPDATE territorios_municipios SET populacao = 25425 WHERE UPPER(TRIM(nome_municipio)) = 'SERRA DO RAMALHO';
UPDATE territorios_municipios SET populacao = 11222 WHERE UPPER(TRIM(nome_municipio)) = 'SÍTIO DO MATO';
UPDATE territorios_municipios SET populacao = 0 WHERE UPPER(TRIM(nome_municipio)) = 'TOTAL GERAL';
UPDATE territorios_municipios SET populacao = 9778 WHERE UPPER(TRIM(nome_municipio)) = 'ANDARAÍ';
UPDATE territorios_municipios SET populacao = 20639 WHERE UPPER(TRIM(nome_municipio)) = 'BARRA DA ESTIVA';
UPDATE territorios_municipios SET populacao = 10911 WHERE UPPER(TRIM(nome_municipio)) = 'BONINAL';
UPDATE territorios_municipios SET populacao = 12332 WHERE UPPER(TRIM(nome_municipio)) = 'BONITO';
UPDATE territorios_municipios SET populacao = 15867 WHERE UPPER(TRIM(nome_municipio)) = 'IBICOARA';
UPDATE territorios_municipios SET populacao = 12212 WHERE UPPER(TRIM(nome_municipio)) = 'IBITIARA';
UPDATE territorios_municipios SET populacao = 8539 WHERE UPPER(TRIM(nome_municipio)) = 'IRAMAIA';
UPDATE territorios_municipios SET populacao = 18664 WHERE UPPER(TRIM(nome_municipio)) = 'IRAQUARA';
UPDATE territorios_municipios SET populacao = 11337 WHERE UPPER(TRIM(nome_municipio)) = 'ITAETÉ';
UPDATE territorios_municipios SET populacao = 6655 WHERE UPPER(TRIM(nome_municipio)) = 'JUSSIAPE';
UPDATE territorios_municipios SET populacao = 7984 WHERE UPPER(TRIM(nome_municipio)) = 'LENÇÓIS';
UPDATE territorios_municipios SET populacao = 7794 WHERE UPPER(TRIM(nome_municipio)) = 'MARCIONÍLIO SOUZA';
UPDATE territorios_municipios SET populacao = 26063 WHERE UPPER(TRIM(nome_municipio)) = 'MORRO DO CHAPÉU';
UPDATE territorios_municipios SET populacao = 9787 WHERE UPPER(TRIM(nome_municipio)) = 'MUCUGÊ';
UPDATE territorios_municipios SET populacao = 6487 WHERE UPPER(TRIM(nome_municipio)) = 'NOVA REDENÇÃO';
UPDATE territorios_municipios SET populacao = 9191 WHERE UPPER(TRIM(nome_municipio)) = 'NOVO HORIZONTE';
UPDATE territorios_municipios SET populacao = 7964 WHERE UPPER(TRIM(nome_municipio)) = 'PALMEIRAS';
UPDATE territorios_municipios SET populacao = 17361 WHERE UPPER(TRIM(nome_municipio)) = 'PIATÃ';
UPDATE territorios_municipios SET populacao = 12194 WHERE UPPER(TRIM(nome_municipio)) = 'RIO DE CONTAS';
UPDATE territorios_municipios SET populacao = 35334 WHERE UPPER(TRIM(nome_municipio)) = 'SEABRA';
UPDATE territorios_municipios SET populacao = 14166 WHERE UPPER(TRIM(nome_municipio)) = 'SOUTO SOARES';
UPDATE territorios_municipios SET populacao = 13285 WHERE UPPER(TRIM(nome_municipio)) = 'UTINGA';
UPDATE territorios_municipios SET populacao = 6876 WHERE UPPER(TRIM(nome_municipio)) = 'WAGNER';
UPDATE territorios_municipios SET populacao = 14845 WHERE UPPER(TRIM(nome_municipio)) = 'BARROCAS';
UPDATE territorios_municipios SET populacao = 13313 WHERE UPPER(TRIM(nome_municipio)) = 'BIRITINGA';
UPDATE territorios_municipios SET populacao = 7810 WHERE UPPER(TRIM(nome_municipio)) = 'CANDEAL';
UPDATE territorios_municipios SET populacao = 28670 WHERE UPPER(TRIM(nome_municipio)) = 'CANSANÇÃO';
UPDATE territorios_municipios SET populacao = 53878 WHERE UPPER(TRIM(nome_municipio)) = 'CONCEIÇÃO DO COITÉ';
UPDATE territorios_municipios SET populacao = 6115 WHERE UPPER(TRIM(nome_municipio)) = 'ICHU';
UPDATE territorios_municipios SET populacao = 27343 WHERE UPPER(TRIM(nome_municipio)) = 'ITIÚBA';
UPDATE territorios_municipios SET populacao = 8639 WHERE UPPER(TRIM(nome_municipio)) = 'LAMARÃO';
UPDATE territorios_municipios SET populacao = 41393 WHERE UPPER(TRIM(nome_municipio)) = 'MONTE SANTO';
UPDATE territorios_municipios SET populacao = 10375 WHERE UPPER(TRIM(nome_municipio)) = 'NORDESTINA';
UPDATE territorios_municipios SET populacao = 20234 WHERE UPPER(TRIM(nome_municipio)) = 'QUEIMADAS';
UPDATE territorios_municipios SET populacao = 20937 WHERE UPPER(TRIM(nome_municipio)) = 'QUIJINGUE';
UPDATE territorios_municipios SET populacao = 12829 WHERE UPPER(TRIM(nome_municipio)) = 'RETIROLÂNDIA';
UPDATE territorios_municipios SET populacao = 31720 WHERE UPPER(TRIM(nome_municipio)) = 'SANTALUZ';
UPDATE territorios_municipios SET populacao = 7978 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO DOMINGOS';
UPDATE territorios_municipios SET populacao = 63726 WHERE UPPER(TRIM(nome_municipio)) = 'SERRINHA';
UPDATE territorios_municipios SET populacao = 18674 WHERE UPPER(TRIM(nome_municipio)) = 'TEOFILÂNDIA';
UPDATE territorios_municipios SET populacao = 41756 WHERE UPPER(TRIM(nome_municipio)) = 'TUCANO';
UPDATE territorios_municipios SET populacao = 19885 WHERE UPPER(TRIM(nome_municipio)) = 'VALENTE';
UPDATE territorios_municipios SET populacao = 6970 WHERE UPPER(TRIM(nome_municipio)) = 'ARATACA';
UPDATE territorios_municipios SET populacao = 10168 WHERE UPPER(TRIM(nome_municipio)) = 'AURELINO LEAL';
UPDATE territorios_municipios SET populacao = 6040 WHERE UPPER(TRIM(nome_municipio)) = 'BARRO PRETO';
UPDATE territorios_municipios SET populacao = 13526 WHERE UPPER(TRIM(nome_municipio)) = 'BUERAREMA';
UPDATE territorios_municipios SET populacao = 17454 WHERE UPPER(TRIM(nome_municipio)) = 'CAMACAN';
UPDATE territorios_municipios SET populacao = 26167 WHERE UPPER(TRIM(nome_municipio)) = 'CANAVIEIRAS';
UPDATE territorios_municipios SET populacao = 15784 WHERE UPPER(TRIM(nome_municipio)) = 'COARACI';
UPDATE territorios_municipios SET populacao = 8021 WHERE UPPER(TRIM(nome_municipio)) = 'FLORESTA AZUL';
UPDATE territorios_municipios SET populacao = 18281 WHERE UPPER(TRIM(nome_municipio)) = 'IBICARAÍ';
UPDATE territorios_municipios SET populacao = 130067 WHERE UPPER(TRIM(nome_municipio)) = 'ILHÉUS';
UPDATE territorios_municipios SET populacao = 141802 WHERE UPPER(TRIM(nome_municipio)) = 'ITABUNA';
UPDATE territorios_municipios SET populacao = 19666 WHERE UPPER(TRIM(nome_municipio)) = 'ITACARÉ';
UPDATE territorios_municipios SET populacao = 6469 WHERE UPPER(TRIM(nome_municipio)) = 'ITAJU DO COLÔNIA';
UPDATE territorios_municipios SET populacao = 16206 WHERE UPPER(TRIM(nome_municipio)) = 'ITAJUÍPE';
UPDATE territorios_municipios SET populacao = 8754 WHERE UPPER(TRIM(nome_municipio)) = 'ITAPÉ';
UPDATE territorios_municipios SET populacao = 6120 WHERE UPPER(TRIM(nome_municipio)) = 'ITAPITANGA';
UPDATE territorios_municipios SET populacao = 4870 WHERE UPPER(TRIM(nome_municipio)) = 'JUSSARI';
UPDATE territorios_municipios SET populacao = 16657 WHERE UPPER(TRIM(nome_municipio)) = 'MARAÚ';
UPDATE territorios_municipios SET populacao = 9473 WHERE UPPER(TRIM(nome_municipio)) = 'MASCOTE';
UPDATE territorios_municipios SET populacao = 7724 WHERE UPPER(TRIM(nome_municipio)) = 'PAU BRASIL';
UPDATE territorios_municipios SET populacao = 9332 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA LUZIA';
UPDATE territorios_municipios SET populacao = 5443 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO JOSÉ DA VITÓRIA';
UPDATE territorios_municipios SET populacao = 14516 WHERE UPPER(TRIM(nome_municipio)) = 'UBAITABA';
UPDATE territorios_municipios SET populacao = 17294 WHERE UPPER(TRIM(nome_municipio)) = 'UNA';
UPDATE territorios_municipios SET populacao = 18530 WHERE UPPER(TRIM(nome_municipio)) = 'URUÇUCA';
UPDATE territorios_municipios SET populacao = 15856 WHERE UPPER(TRIM(nome_municipio)) = 'CAIRU';
UPDATE territorios_municipios SET populacao = 24611 WHERE UPPER(TRIM(nome_municipio)) = 'CAMAMU';
UPDATE territorios_municipios SET populacao = 23410 WHERE UPPER(TRIM(nome_municipio)) = 'GANDU';
UPDATE territorios_municipios SET populacao = 14926 WHERE UPPER(TRIM(nome_municipio)) = 'IBIRAPITANGA';
UPDATE territorios_municipios SET populacao = 9181 WHERE UPPER(TRIM(nome_municipio)) = 'IGRAPIÚNA';
UPDATE territorios_municipios SET populacao = 17869 WHERE UPPER(TRIM(nome_municipio)) = 'ITUBERÁ';
UPDATE territorios_municipios SET populacao = 15396 WHERE UPPER(TRIM(nome_municipio)) = 'JAGUARIPE';
UPDATE territorios_municipios SET populacao = 9935 WHERE UPPER(TRIM(nome_municipio)) = 'NILO PEÇANHA';
UPDATE territorios_municipios SET populacao = 7245 WHERE UPPER(TRIM(nome_municipio)) = 'PIRAÍ DO NORTE';
UPDATE territorios_municipios SET populacao = 21519 WHERE UPPER(TRIM(nome_municipio)) = 'PRESIDENTE TANCREDO NEVES';
UPDATE territorios_municipios SET populacao = 14366 WHERE UPPER(TRIM(nome_municipio)) = 'TAPEROÁ';
UPDATE territorios_municipios SET populacao = 11431 WHERE UPPER(TRIM(nome_municipio)) = 'TEOLÂNDIA';
UPDATE territorios_municipios SET populacao = 66502 WHERE UPPER(TRIM(nome_municipio)) = 'VALENÇA';
UPDATE territorios_municipios SET populacao = 16706 WHERE UPPER(TRIM(nome_municipio)) = 'WENCESLAU GUIMARÃES';
UPDATE territorios_municipios SET populacao = 84917 WHERE UPPER(TRIM(nome_municipio)) = 'EUNÁPOLIS';
UPDATE territorios_municipios SET populacao = 15779 WHERE UPPER(TRIM(nome_municipio)) = 'GUARATINGA';
UPDATE territorios_municipios SET populacao = 22365 WHERE UPPER(TRIM(nome_municipio)) = 'ITABELA';
UPDATE territorios_municipios SET populacao = 6784 WHERE UPPER(TRIM(nome_municipio)) = 'ITAGIMIRIM';
UPDATE territorios_municipios SET populacao = 8662 WHERE UPPER(TRIM(nome_municipio)) = 'ITAPEBI';
UPDATE territorios_municipios SET populacao = 114539 WHERE UPPER(TRIM(nome_municipio)) = 'PORTO SEGURO';
UPDATE territorios_municipios SET populacao = 26318 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA CRUZ CABRÁLIA';
UPDATE territorios_municipios SET populacao = 16555 WHERE UPPER(TRIM(nome_municipio)) = 'CARAVELAS';
UPDATE territorios_municipios SET populacao = 7537 WHERE UPPER(TRIM(nome_municipio)) = 'IBIRAPUÃ';
UPDATE territorios_municipios SET populacao = 45630 WHERE UPPER(TRIM(nome_municipio)) = 'ITAMARAJU';
UPDATE territorios_municipios SET populacao = 15291 WHERE UPPER(TRIM(nome_municipio)) = 'ITANHÉM';
UPDATE territorios_municipios SET populacao = 8611 WHERE UPPER(TRIM(nome_municipio)) = 'JUCURUÇU';
UPDATE territorios_municipios SET populacao = 4643 WHERE UPPER(TRIM(nome_municipio)) = 'LAJEDÃO';
UPDATE territorios_municipios SET populacao = 18802 WHERE UPPER(TRIM(nome_municipio)) = 'MEDEIROS NETO';
UPDATE territorios_municipios SET populacao = 28908 WHERE UPPER(TRIM(nome_municipio)) = 'MUCURI';
UPDATE territorios_municipios SET populacao = 30720 WHERE UPPER(TRIM(nome_municipio)) = 'NOVA VIÇOSA';
UPDATE territorios_municipios SET populacao = 25069 WHERE UPPER(TRIM(nome_municipio)) = 'PRADO';
UPDATE territorios_municipios SET populacao = 104743 WHERE UPPER(TRIM(nome_municipio)) = 'TEIXEIRA DE FREITAS';
UPDATE territorios_municipios SET populacao = 6976 WHERE UPPER(TRIM(nome_municipio)) = 'VEREDA';
UPDATE territorios_municipios SET populacao = 6040 WHERE UPPER(TRIM(nome_municipio)) = 'FIRMINO ALVES';
UPDATE territorios_municipios SET populacao = 11690 WHERE UPPER(TRIM(nome_municipio)) = 'IBICUÍ';
UPDATE territorios_municipios SET populacao = 17974 WHERE UPPER(TRIM(nome_municipio)) = 'IGUAÍ';
UPDATE territorios_municipios SET populacao = 18071 WHERE UPPER(TRIM(nome_municipio)) = 'ITAMBÉ';
UPDATE territorios_municipios SET populacao = 47855 WHERE UPPER(TRIM(nome_municipio)) = 'ITAPETINGA';
UPDATE territorios_municipios SET populacao = 13975 WHERE UPPER(TRIM(nome_municipio)) = 'ITARANTIM';
UPDATE territorios_municipios SET populacao = 16313 WHERE UPPER(TRIM(nome_municipio)) = 'ITORORÓ';
UPDATE territorios_municipios SET populacao = 12976 WHERE UPPER(TRIM(nome_municipio)) = 'MACARANI';
UPDATE territorios_municipios SET populacao = 7466 WHERE UPPER(TRIM(nome_municipio)) = 'MAIQUINIQUE';
UPDATE territorios_municipios SET populacao = 12719 WHERE UPPER(TRIM(nome_municipio)) = 'NOVA CANAÃ';
UPDATE territorios_municipios SET populacao = 8123 WHERE UPPER(TRIM(nome_municipio)) = 'POTIRAGUÁ';
UPDATE territorios_municipios SET populacao = 5073 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA CRUZ DA VITÓRIA';
UPDATE territorios_municipios SET populacao = 10954 WHERE UPPER(TRIM(nome_municipio)) = 'BREJÕES';
UPDATE territorios_municipios SET populacao = 4585 WHERE UPPER(TRIM(nome_municipio)) = 'CRAVOLÂNDIA';
UPDATE territorios_municipios SET populacao = 7732 WHERE UPPER(TRIM(nome_municipio)) = 'ELÍSIO MEDRADO';
UPDATE territorios_municipios SET populacao = 5648 WHERE UPPER(TRIM(nome_municipio)) = 'IRAJUBA';
UPDATE territorios_municipios SET populacao = 6970 WHERE UPPER(TRIM(nome_municipio)) = 'ITAQUARA';
UPDATE territorios_municipios SET populacao = 9101 WHERE UPPER(TRIM(nome_municipio)) = 'ITIRUÇU';
UPDATE territorios_municipios SET populacao = 36008 WHERE UPPER(TRIM(nome_municipio)) = 'JAGUAQUARA';
UPDATE territorios_municipios SET populacao = 11350 WHERE UPPER(TRIM(nome_municipio)) = 'JIQUIRIÇÁ';
UPDATE territorios_municipios SET populacao = 4517 WHERE UPPER(TRIM(nome_municipio)) = 'LAFAIETE COUTINHO';
UPDATE territorios_municipios SET populacao = 20463 WHERE UPPER(TRIM(nome_municipio)) = 'LAJE';
UPDATE territorios_municipios SET populacao = 6380 WHERE UPPER(TRIM(nome_municipio)) = 'LAJEDO DO TABOCAL';
UPDATE territorios_municipios SET populacao = 21103 WHERE UPPER(TRIM(nome_municipio)) = 'MARACÁS';
UPDATE territorios_municipios SET populacao = 8849 WHERE UPPER(TRIM(nome_municipio)) = 'MILAGRES';
UPDATE territorios_municipios SET populacao = 17846 WHERE UPPER(TRIM(nome_municipio)) = 'MUTUÍPE';
UPDATE territorios_municipios SET populacao = 6518 WHERE UPPER(TRIM(nome_municipio)) = 'NOVA ITARANA';
UPDATE territorios_municipios SET populacao = 7002 WHERE UPPER(TRIM(nome_municipio)) = 'PLANALTINO';
UPDATE territorios_municipios SET populacao = 8176 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA INÊS';
UPDATE territorios_municipios SET populacao = 9140 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO MIGUEL DAS MATAS';
UPDATE territorios_municipios SET populacao = 15903 WHERE UPPER(TRIM(nome_municipio)) = 'UBAÍRA';
UPDATE territorios_municipios SET populacao = 12996 WHERE UPPER(TRIM(nome_municipio)) = 'CANUDOS';
UPDATE territorios_municipios SET populacao = 56680 WHERE UPPER(TRIM(nome_municipio)) = 'CASA NOVA';
UPDATE territorios_municipios SET populacao = 27085 WHERE UPPER(TRIM(nome_municipio)) = 'CURAÇÁ';
UPDATE territorios_municipios SET populacao = 160673 WHERE UPPER(TRIM(nome_municipio)) = 'JUAZEIRO';
UPDATE territorios_municipios SET populacao = 28399 WHERE UPPER(TRIM(nome_municipio)) = 'PILÃO ARCADO';
UPDATE territorios_municipios SET populacao = 31725 WHERE UPPER(TRIM(nome_municipio)) = 'REMANSO';
UPDATE territorios_municipios SET populacao = 30170 WHERE UPPER(TRIM(nome_municipio)) = 'SENTO SÉ';
UPDATE territorios_municipios SET populacao = 20570 WHERE UPPER(TRIM(nome_municipio)) = 'SOBRADINHO';
UPDATE territorios_municipios SET populacao = 21886 WHERE UPPER(TRIM(nome_municipio)) = 'UAUÁ';
UPDATE territorios_municipios SET populacao = 12523 WHERE UPPER(TRIM(nome_municipio)) = 'BAIANÓPOLIS';
UPDATE territorios_municipios SET populacao = 107089 WHERE UPPER(TRIM(nome_municipio)) = 'BARREIRAS';
UPDATE territorios_municipios SET populacao = 15667 WHERE UPPER(TRIM(nome_municipio)) = 'BURITIRAMA';
UPDATE territorios_municipios SET populacao = 4492 WHERE UPPER(TRIM(nome_municipio)) = 'CATOLÂNDIA';
UPDATE territorios_municipios SET populacao = 11931 WHERE UPPER(TRIM(nome_municipio)) = 'COTEGIPE';
UPDATE territorios_municipios SET populacao = 12471 WHERE UPPER(TRIM(nome_municipio)) = 'CRISTÓPOLIS';
UPDATE territorios_municipios SET populacao = 20247 WHERE UPPER(TRIM(nome_municipio)) = 'FORMOSA DO RIO PRETO';
UPDATE territorios_municipios SET populacao = 75135 WHERE UPPER(TRIM(nome_municipio)) = 'LUÍS EDUARDO MAGALHÃES';
UPDATE territorios_municipios SET populacao = 10784 WHERE UPPER(TRIM(nome_municipio)) = 'MANSIDÃO';
UPDATE territorios_municipios SET populacao = 19775 WHERE UPPER(TRIM(nome_municipio)) = 'RIACHÃO DAS NEVES';
UPDATE territorios_municipios SET populacao = 23002 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA RITA DE CÁSSIA';
UPDATE territorios_municipios SET populacao = 28156 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO DESIDÉRIO';
UPDATE territorios_municipios SET populacao = 10783 WHERE UPPER(TRIM(nome_municipio)) = 'WANDERLEY';
UPDATE territorios_municipios SET populacao = 17913 WHERE UPPER(TRIM(nome_municipio)) = 'CACULÉ';
UPDATE territorios_municipios SET populacao = 41698 WHERE UPPER(TRIM(nome_municipio)) = 'CAETITÉ';
UPDATE territorios_municipios SET populacao = 11559 WHERE UPPER(TRIM(nome_municipio)) = 'CANDIBA';
UPDATE territorios_municipios SET populacao = 4564 WHERE UPPER(TRIM(nome_municipio)) = 'CONTENDAS DO SINCORÁ';
UPDATE territorios_municipios SET populacao = 10611 WHERE UPPER(TRIM(nome_municipio)) = 'DOM BASÍLIO';
UPDATE territorios_municipios SET populacao = 66413 WHERE UPPER(TRIM(nome_municipio)) = 'GUANAMBI';
UPDATE territorios_municipios SET populacao = 8440 WHERE UPPER(TRIM(nome_municipio)) = 'IBIASSUCÊ';
UPDATE territorios_municipios SET populacao = 15554 WHERE UPPER(TRIM(nome_municipio)) = 'ITUAÇU';
UPDATE territorios_municipios SET populacao = 8727 WHERE UPPER(TRIM(nome_municipio)) = 'IUIÚ';
UPDATE territorios_municipios SET populacao = 10649 WHERE UPPER(TRIM(nome_municipio)) = 'LAGOA REAL';
UPDATE territorios_municipios SET populacao = 34208 WHERE UPPER(TRIM(nome_municipio)) = 'LIVRAMENTO DE NOSSA SENHORA';
UPDATE territorios_municipios SET populacao = 7910 WHERE UPPER(TRIM(nome_municipio)) = 'MALHADA DE PEDRAS';
UPDATE territorios_municipios SET populacao = 17289 WHERE UPPER(TRIM(nome_municipio)) = 'PALMAS DE MONTE ALTO';
UPDATE territorios_municipios SET populacao = 12635 WHERE UPPER(TRIM(nome_municipio)) = 'PINDAÍ';
UPDATE territorios_municipios SET populacao = 10667 WHERE UPPER(TRIM(nome_municipio)) = 'RIO DO ANTÔNIO';
UPDATE territorios_municipios SET populacao = 7237 WHERE UPPER(TRIM(nome_municipio)) = 'SEBASTIÃO LARANJEIRAS';
UPDATE territorios_municipios SET populacao = 17795 WHERE UPPER(TRIM(nome_municipio)) = 'TANHAÇU';
UPDATE territorios_municipios SET populacao = 14447 WHERE UPPER(TRIM(nome_municipio)) = 'TANQUE NOVO';
UPDATE territorios_municipios SET populacao = 13682 WHERE UPPER(TRIM(nome_municipio)) = 'URANDI';
UPDATE territorios_municipios SET populacao = 9628 WHERE UPPER(TRIM(nome_municipio)) = 'BOTUPORÃ';
UPDATE territorios_municipios SET populacao = 7215 WHERE UPPER(TRIM(nome_municipio)) = 'CATURAMA';
UPDATE territorios_municipios SET populacao = 8631 WHERE UPPER(TRIM(nome_municipio)) = 'ÉRICO CARDOSO';
UPDATE territorios_municipios SET populacao = 13119 WHERE UPPER(TRIM(nome_municipio)) = 'IBIPITANGA';
UPDATE territorios_municipios SET populacao = 33080 WHERE UPPER(TRIM(nome_municipio)) = 'MACAÚBAS';
UPDATE territorios_municipios SET populacao = 16927 WHERE UPPER(TRIM(nome_municipio)) = 'PARAMIRIM';
UPDATE territorios_municipios SET populacao = 11828 WHERE UPPER(TRIM(nome_municipio)) = 'RIO DO PIRES';
UPDATE territorios_municipios SET populacao = 20413 WHERE UPPER(TRIM(nome_municipio)) = 'IAÇU';
UPDATE territorios_municipios SET populacao = 4289 WHERE UPPER(TRIM(nome_municipio)) = 'IBIQUERA';
UPDATE territorios_municipios SET populacao = 48076 WHERE UPPER(TRIM(nome_municipio)) = 'ITABERABA';
UPDATE territorios_municipios SET populacao = 12841 WHERE UPPER(TRIM(nome_municipio)) = 'ITATIM';
UPDATE territorios_municipios SET populacao = 3643 WHERE UPPER(TRIM(nome_municipio)) = 'LAJEDINHO';
UPDATE territorios_municipios SET populacao = 10074 WHERE UPPER(TRIM(nome_municipio)) = 'MACAJUBA';
UPDATE territorios_municipios SET populacao = 15075 WHERE UPPER(TRIM(nome_municipio)) = 'MUNDO NOVO';
UPDATE territorios_municipios SET populacao = 14240 WHERE UPPER(TRIM(nome_municipio)) = 'PIRITIBA';
UPDATE territorios_municipios SET populacao = 18835 WHERE UPPER(TRIM(nome_municipio)) = 'RAFAEL JAMBEIRO';
UPDATE territorios_municipios SET populacao = 23765 WHERE UPPER(TRIM(nome_municipio)) = 'RUY BARBOSA';
UPDATE territorios_municipios SET populacao = 9243 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA TERESINHA';
UPDATE territorios_municipios SET populacao = 11206 WHERE UPPER(TRIM(nome_municipio)) = 'TAPIRAMUTÁ';
UPDATE territorios_municipios SET populacao = 9669 WHERE UPPER(TRIM(nome_municipio)) = 'CAPELA DO ALTO ALEGRE';
UPDATE territorios_municipios SET populacao = 24172 WHERE UPPER(TRIM(nome_municipio)) = 'CAPIM GROSSO';
UPDATE territorios_municipios SET populacao = 4376 WHERE UPPER(TRIM(nome_municipio)) = 'GAVIÃO';
UPDATE territorios_municipios SET populacao = 48556 WHERE UPPER(TRIM(nome_municipio)) = 'IPIRÁ';
UPDATE territorios_municipios SET populacao = 13735 WHERE UPPER(TRIM(nome_municipio)) = 'MAIRI';
UPDATE territorios_municipios SET populacao = 7984 WHERE UPPER(TRIM(nome_municipio)) = 'NOVA FÁTIMA';
UPDATE territorios_municipios SET populacao = 12098 WHERE UPPER(TRIM(nome_municipio)) = 'PÉ DE SERRA';
UPDATE territorios_municipios SET populacao = 9059 WHERE UPPER(TRIM(nome_municipio)) = 'PINTADAS';
UPDATE territorios_municipios SET populacao = 8845 WHERE UPPER(TRIM(nome_municipio)) = 'QUIXABEIRA';
UPDATE territorios_municipios SET populacao = 27529 WHERE UPPER(TRIM(nome_municipio)) = 'RIACHÃO DO JACUÍPE';
UPDATE territorios_municipios SET populacao = 8830 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO JOSÉ DO JACUÍPE';
UPDATE territorios_municipios SET populacao = 17359 WHERE UPPER(TRIM(nome_municipio)) = 'SERRA PRETA';
UPDATE territorios_municipios SET populacao = 10902 WHERE UPPER(TRIM(nome_municipio)) = 'VÁRZEA DA ROÇA';
UPDATE territorios_municipios SET populacao = 7211 WHERE UPPER(TRIM(nome_municipio)) = 'VÁRZEA DO POÇO';
UPDATE territorios_municipios SET populacao = 61848 WHERE UPPER(TRIM(nome_municipio)) = 'JACOBINA';
UPDATE territorios_municipios SET populacao = 19849 WHERE UPPER(TRIM(nome_municipio)) = 'MIGUEL CALMON';
UPDATE territorios_municipios SET populacao = 12688 WHERE UPPER(TRIM(nome_municipio)) = 'MIRANGABA';
UPDATE territorios_municipios SET populacao = 14597 WHERE UPPER(TRIM(nome_municipio)) = 'OUROLÂNDIA';
UPDATE territorios_municipios SET populacao = 9231 WHERE UPPER(TRIM(nome_municipio)) = 'SAÚDE';
UPDATE territorios_municipios SET populacao = 11154 WHERE UPPER(TRIM(nome_municipio)) = 'SERROLÂNDIA';
UPDATE territorios_municipios SET populacao = 11931 WHERE UPPER(TRIM(nome_municipio)) = 'UMBURANAS';
UPDATE territorios_municipios SET populacao = 10823 WHERE UPPER(TRIM(nome_municipio)) = 'VÁRZEA NOVA';
UPDATE territorios_municipios SET populacao = 10816 WHERE UPPER(TRIM(nome_municipio)) = 'ANTAS';
UPDATE territorios_municipios SET populacao = 11060 WHERE UPPER(TRIM(nome_municipio)) = 'BANZAÊ';
UPDATE territorios_municipios SET populacao = 26064 WHERE UPPER(TRIM(nome_municipio)) = 'CÍCERO DANTAS';
UPDATE territorios_municipios SET populacao = 14890 WHERE UPPER(TRIM(nome_municipio)) = 'CIPÓ';
UPDATE territorios_municipios SET populacao = 15062 WHERE UPPER(TRIM(nome_municipio)) = 'CORONEL JOÃO SÁ';
UPDATE territorios_municipios SET populacao = 45081 WHERE UPPER(TRIM(nome_municipio)) = 'EUCLIDES DA CUNHA';
UPDATE territorios_municipios SET populacao = 15276 WHERE UPPER(TRIM(nome_municipio)) = 'FÁTIMA';
UPDATE territorios_municipios SET populacao = 12948 WHERE UPPER(TRIM(nome_municipio)) = 'HELIÓPOLIS';
UPDATE territorios_municipios SET populacao = 28561 WHERE UPPER(TRIM(nome_municipio)) = 'JEREMOABO';
UPDATE territorios_municipios SET populacao = 20973 WHERE UPPER(TRIM(nome_municipio)) = 'NOVA SOURE';
UPDATE territorios_municipios SET populacao = 8351 WHERE UPPER(TRIM(nome_municipio)) = 'NOVO TRIUNFO';
UPDATE territorios_municipios SET populacao = 23542 WHERE UPPER(TRIM(nome_municipio)) = 'PARIPIRANGA';
UPDATE territorios_municipios SET populacao = 10180 WHERE UPPER(TRIM(nome_municipio)) = 'PEDRO ALEXANDRE';
UPDATE territorios_municipios SET populacao = 12185 WHERE UPPER(TRIM(nome_municipio)) = 'RIBEIRA DO AMPARO';
UPDATE territorios_municipios SET populacao = 44535 WHERE UPPER(TRIM(nome_municipio)) = 'RIBEIRA DO POMBAL';
UPDATE territorios_municipios SET populacao = 11841 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA BRÍGIDA';
UPDATE territorios_municipios SET populacao = 9801 WHERE UPPER(TRIM(nome_municipio)) = 'SÍTIO DO QUINTO';
UPDATE territorios_municipios SET populacao = 114306 WHERE UPPER(TRIM(nome_municipio)) = 'ALAGOINHAS';
UPDATE territorios_municipios SET populacao = 13968 WHERE UPPER(TRIM(nome_municipio)) = 'APORÁ';
UPDATE territorios_municipios SET populacao = 10991 WHERE UPPER(TRIM(nome_municipio)) = 'ARAÇÁS';
UPDATE territorios_municipios SET populacao = 9943 WHERE UPPER(TRIM(nome_municipio)) = 'ARAMARI';
UPDATE territorios_municipios SET populacao = 8023 WHERE UPPER(TRIM(nome_municipio)) = 'CARDEAL DA SILVA';
UPDATE territorios_municipios SET populacao = 41165 WHERE UPPER(TRIM(nome_municipio)) = 'CATU';
UPDATE territorios_municipios SET populacao = 18792 WHERE UPPER(TRIM(nome_municipio)) = 'CONDE';
UPDATE territorios_municipios SET populacao = 16726 WHERE UPPER(TRIM(nome_municipio)) = 'CRISÓPOLIS';
UPDATE territorios_municipios SET populacao = 31500 WHERE UPPER(TRIM(nome_municipio)) = 'ENTRE RIOS';
UPDATE territorios_municipios SET populacao = 26850 WHERE UPPER(TRIM(nome_municipio)) = 'ESPLANADA';
UPDATE territorios_municipios SET populacao = 27434 WHERE UPPER(TRIM(nome_municipio)) = 'INHAMBUPE';
UPDATE territorios_municipios SET populacao = 7014 WHERE UPPER(TRIM(nome_municipio)) = 'ITANAGRA';
UPDATE territorios_municipios SET populacao = 23276 WHERE UPPER(TRIM(nome_municipio)) = 'ITAPICURU';
UPDATE territorios_municipios SET populacao = 9119 WHERE UPPER(TRIM(nome_municipio)) = 'JANDAÍRA';
UPDATE territorios_municipios SET populacao = 19751 WHERE UPPER(TRIM(nome_municipio)) = 'OLINDINA';
UPDATE territorios_municipios SET populacao = 7210 WHERE UPPER(TRIM(nome_municipio)) = 'OURIÇANGAS';
UPDATE territorios_municipios SET populacao = 6671 WHERE UPPER(TRIM(nome_municipio)) = 'PEDRÃO';
UPDATE territorios_municipios SET populacao = 28750 WHERE UPPER(TRIM(nome_municipio)) = 'RIO REAL';
UPDATE territorios_municipios SET populacao = 13981 WHERE UPPER(TRIM(nome_municipio)) = 'SÁTIRO DIAS';
UPDATE territorios_municipios SET populacao = 19490 WHERE UPPER(TRIM(nome_municipio)) = 'AMÉLIA RODRIGUES';
UPDATE territorios_municipios SET populacao = 10012 WHERE UPPER(TRIM(nome_municipio)) = 'ANGUERA';
UPDATE territorios_municipios SET populacao = 12264 WHERE UPPER(TRIM(nome_municipio)) = 'ANTÔNIO CARDOSO';
UPDATE territorios_municipios SET populacao = 17467 WHERE UPPER(TRIM(nome_municipio)) = 'CONCEIÇÃO DA FEIRA';
UPDATE territorios_municipios SET populacao = 28567 WHERE UPPER(TRIM(nome_municipio)) = 'CONCEIÇÃO DO JACUÍPE';
UPDATE territorios_municipios SET populacao = 22052 WHERE UPPER(TRIM(nome_municipio)) = 'CORAÇÃO DE MARIA';
UPDATE territorios_municipios SET populacao = 426887 WHERE UPPER(TRIM(nome_municipio)) = 'FEIRA DE SANTANA';
UPDATE territorios_municipios SET populacao = 15249 WHERE UPPER(TRIM(nome_municipio)) = 'IPECAETÁ';
UPDATE territorios_municipios SET populacao = 25132 WHERE UPPER(TRIM(nome_municipio)) = 'IRARÁ';
UPDATE territorios_municipios SET populacao = 19960 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA BÁRBARA';
UPDATE territorios_municipios SET populacao = 9650 WHERE UPPER(TRIM(nome_municipio)) = 'SANTANÓPOLIS';
UPDATE territorios_municipios SET populacao = 39119 WHERE UPPER(TRIM(nome_municipio)) = 'SANTO ESTEVÃO';
UPDATE territorios_municipios SET populacao = 29931 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO GONÇALO DOS CAMPOS';
UPDATE territorios_municipios SET populacao = 7705 WHERE UPPER(TRIM(nome_municipio)) = 'TANQUINHO';
UPDATE territorios_municipios SET populacao = 6930 WHERE UPPER(TRIM(nome_municipio)) = 'TEODORO SAMPAIO';
UPDATE territorios_municipios SET populacao = 10438 WHERE UPPER(TRIM(nome_municipio)) = 'TERRA NOVA';
UPDATE territorios_municipios SET populacao = 12581 WHERE UPPER(TRIM(nome_municipio)) = 'ARACATU';
UPDATE territorios_municipios SET populacao = 28632 WHERE UPPER(TRIM(nome_municipio)) = 'BARRA DO CHOÇA';
UPDATE territorios_municipios SET populacao = 15721 WHERE UPPER(TRIM(nome_municipio)) = 'BELO CAMPO';
UPDATE territorios_municipios SET populacao = 9384 WHERE UPPER(TRIM(nome_municipio)) = 'BOM JESUS DA SERRA';
UPDATE territorios_municipios SET populacao = 11112 WHERE UPPER(TRIM(nome_municipio)) = 'CAETANOS';
UPDATE territorios_municipios SET populacao = 21088 WHERE UPPER(TRIM(nome_municipio)) = 'CÂNDIDO SALES';
UPDATE territorios_municipios SET populacao = 8550 WHERE UPPER(TRIM(nome_municipio)) = 'CARAÍBAS';
UPDATE territorios_municipios SET populacao = 15357 WHERE UPPER(TRIM(nome_municipio)) = 'CONDEÚBA';
UPDATE territorios_municipios SET populacao = 7254 WHERE UPPER(TRIM(nome_municipio)) = 'CORDEIROS';
UPDATE territorios_municipios SET populacao = 15960 WHERE UPPER(TRIM(nome_municipio)) = 'ENCRUZILHADA';
UPDATE territorios_municipios SET populacao = 6518 WHERE UPPER(TRIM(nome_municipio)) = 'GUAJERU';
UPDATE territorios_municipios SET populacao = 11814 WHERE UPPER(TRIM(nome_municipio)) = 'JACARACI';
UPDATE territorios_municipios SET populacao = 9872 WHERE UPPER(TRIM(nome_municipio)) = 'LICÍNIO DE ALMEIDA';
UPDATE territorios_municipios SET populacao = 6822 WHERE UPPER(TRIM(nome_municipio)) = 'MAETINGA';
UPDATE territorios_municipios SET populacao = 8079 WHERE UPPER(TRIM(nome_municipio)) = 'MIRANTE';
UPDATE territorios_municipios SET populacao = 9534 WHERE UPPER(TRIM(nome_municipio)) = 'MORTUGABA';
UPDATE territorios_municipios SET populacao = 9080 WHERE UPPER(TRIM(nome_municipio)) = 'PIRIPÁ';
UPDATE territorios_municipios SET populacao = 20297 WHERE UPPER(TRIM(nome_municipio)) = 'PLANALTO';
UPDATE territorios_municipios SET populacao = 36985 WHERE UPPER(TRIM(nome_municipio)) = 'POÇÕES';
UPDATE territorios_municipios SET populacao = 10715 WHERE UPPER(TRIM(nome_municipio)) = 'PRESIDENTE JÂNIO QUADROS';
UPDATE territorios_municipios SET populacao = 9072 WHERE UPPER(TRIM(nome_municipio)) = 'RIBEIRÃO DO LARGO';
UPDATE territorios_municipios SET populacao = 15527 WHERE UPPER(TRIM(nome_municipio)) = 'TREMEDAL';
UPDATE territorios_municipios SET populacao = 257784 WHERE UPPER(TRIM(nome_municipio)) = 'VITÓRIA DA CONQUISTA';
UPDATE territorios_municipios SET populacao = 25643 WHERE UPPER(TRIM(nome_municipio)) = 'CACHOEIRA';
UPDATE territorios_municipios SET populacao = 22753 WHERE UPPER(TRIM(nome_municipio)) = 'CASTRO ALVES';
UPDATE territorios_municipios SET populacao = 14360 WHERE UPPER(TRIM(nome_municipio)) = 'CONCEIÇÃO DO ALMEIDA';
UPDATE territorios_municipios SET populacao = 49017 WHERE UPPER(TRIM(nome_municipio)) = 'CRUZ DAS ALMAS';
UPDATE territorios_municipios SET populacao = 4913 WHERE UPPER(TRIM(nome_municipio)) = 'DOM MACEDO COSTA';
UPDATE territorios_municipios SET populacao = 18932 WHERE UPPER(TRIM(nome_municipio)) = 'GOVERNADOR MANGABEIRA';
UPDATE territorios_municipios SET populacao = 34470 WHERE UPPER(TRIM(nome_municipio)) = 'MARAGOGIPE';
UPDATE territorios_municipios SET populacao = 8372 WHERE UPPER(TRIM(nome_municipio)) = 'MUNIZ FERREIRA';
UPDATE territorios_municipios SET populacao = 23951 WHERE UPPER(TRIM(nome_municipio)) = 'MURITIBA';
UPDATE territorios_municipios SET populacao = 21842 WHERE UPPER(TRIM(nome_municipio)) = 'NAZARÉ';
UPDATE territorios_municipios SET populacao = 15646 WHERE UPPER(TRIM(nome_municipio)) = 'SALINAS DA MARGARIDA';
UPDATE territorios_municipios SET populacao = 47931 WHERE UPPER(TRIM(nome_municipio)) = 'SANTO AMARO';
UPDATE territorios_municipios SET populacao = 78195 WHERE UPPER(TRIM(nome_municipio)) = 'SANTO ANTÔNIO DE JESUS';
UPDATE territorios_municipios SET populacao = 10176 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO FÉLIX';
UPDATE territorios_municipios SET populacao = 17604 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO FELIPE';
UPDATE territorios_municipios SET populacao = 16229 WHERE UPPER(TRIM(nome_municipio)) = 'SAPEAÇU';
UPDATE territorios_municipios SET populacao = 13577 WHERE UPPER(TRIM(nome_municipio)) = 'SAUBARA';
UPDATE territorios_municipios SET populacao = 9542 WHERE UPPER(TRIM(nome_municipio)) = 'VARZEDO';
UPDATE territorios_municipios SET populacao = 6415 WHERE UPPER(TRIM(nome_municipio)) = 'APUAREMA';
UPDATE territorios_municipios SET populacao = 4710 WHERE UPPER(TRIM(nome_municipio)) = 'BARRA DO ROCHA';
UPDATE territorios_municipios SET populacao = 12960 WHERE UPPER(TRIM(nome_municipio)) = 'BOA NOVA';
UPDATE territorios_municipios SET populacao = 8684 WHERE UPPER(TRIM(nome_municipio)) = 'DÁRIO MEIRA';
UPDATE territorios_municipios SET populacao = 5758 WHERE UPPER(TRIM(nome_municipio)) = 'GONGOGI';
UPDATE territorios_municipios SET populacao = 16263 WHERE UPPER(TRIM(nome_municipio)) = 'IBIRATAIA';
UPDATE territorios_municipios SET populacao = 33006 WHERE UPPER(TRIM(nome_municipio)) = 'IPIAÚ';
UPDATE territorios_municipios SET populacao = 10928 WHERE UPPER(TRIM(nome_municipio)) = 'ITAGI';
UPDATE territorios_municipios SET populacao = 13387 WHERE UPPER(TRIM(nome_municipio)) = 'ITAGIBÁ';
UPDATE territorios_municipios SET populacao = 6303 WHERE UPPER(TRIM(nome_municipio)) = 'ITAMARI';
UPDATE territorios_municipios SET populacao = 118674 WHERE UPPER(TRIM(nome_municipio)) = 'JEQUIÉ';
UPDATE territorios_municipios SET populacao = 12924 WHERE UPPER(TRIM(nome_municipio)) = 'JITAÚNA';
UPDATE territorios_municipios SET populacao = 13444 WHERE UPPER(TRIM(nome_municipio)) = 'MANOEL VITORINO';
UPDATE territorios_municipios SET populacao = 5614 WHERE UPPER(TRIM(nome_municipio)) = 'NOVA IBIÁ';
UPDATE territorios_municipios SET populacao = 12317 WHERE UPPER(TRIM(nome_municipio)) = 'UBATÃ';
UPDATE territorios_municipios SET populacao = 8804 WHERE UPPER(TRIM(nome_municipio)) = 'CANÁPOLIS';
UPDATE territorios_municipios SET populacao = 16662 WHERE UPPER(TRIM(nome_municipio)) = 'CÔCOS';
UPDATE territorios_municipios SET populacao = 13038 WHERE UPPER(TRIM(nome_municipio)) = 'CORIBE';
UPDATE territorios_municipios SET populacao = 27807 WHERE UPPER(TRIM(nome_municipio)) = 'CORRENTINA';
UPDATE territorios_municipios SET populacao = 10500 WHERE UPPER(TRIM(nome_municipio)) = 'JABORANDI';
UPDATE territorios_municipios SET populacao = 30131 WHERE UPPER(TRIM(nome_municipio)) = 'SANTA MARIA DA VITÓRIA';
UPDATE territorios_municipios SET populacao = 20814 WHERE UPPER(TRIM(nome_municipio)) = 'SANTANA';
UPDATE territorios_municipios SET populacao = 12778 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO FÉLIX DO CORIBE';
UPDATE territorios_municipios SET populacao = 15475 WHERE UPPER(TRIM(nome_municipio)) = 'SERRA DOURADA';
UPDATE territorios_municipios SET populacao = 11403 WHERE UPPER(TRIM(nome_municipio)) = 'TABOCAS DO BREJO VELHO';
UPDATE territorios_municipios SET populacao = 8925 WHERE UPPER(TRIM(nome_municipio)) = 'CHORROCHÓ';
UPDATE territorios_municipios SET populacao = 13178 WHERE UPPER(TRIM(nome_municipio)) = 'GLÓRIA';
UPDATE territorios_municipios SET populacao = 6610 WHERE UPPER(TRIM(nome_municipio)) = 'MACURURÉ';
UPDATE territorios_municipios SET populacao = 82857 WHERE UPPER(TRIM(nome_municipio)) = 'PAULO AFONSO';
UPDATE territorios_municipios SET populacao = 7561 WHERE UPPER(TRIM(nome_municipio)) = 'RODELAS';
UPDATE territorios_municipios SET populacao = 8882 WHERE UPPER(TRIM(nome_municipio)) = 'ANTÔNIO GONÇALVES';
UPDATE territorios_municipios SET populacao = 10510 WHERE UPPER(TRIM(nome_municipio)) = 'CALDEIRÃO GRANDE';
UPDATE territorios_municipios SET populacao = 57312 WHERE UPPER(TRIM(nome_municipio)) = 'CAMPO FORMOSO';
UPDATE territorios_municipios SET populacao = 15265 WHERE UPPER(TRIM(nome_municipio)) = 'FILADÉLFIA';
UPDATE territorios_municipios SET populacao = 22187 WHERE UPPER(TRIM(nome_municipio)) = 'JAGUARARI';
UPDATE territorios_municipios SET populacao = 16063 WHERE UPPER(TRIM(nome_municipio)) = 'PINDOBAÇU';
UPDATE territorios_municipios SET populacao = 14814 WHERE UPPER(TRIM(nome_municipio)) = 'PONTO NOVO';
UPDATE territorios_municipios SET populacao = 53406 WHERE UPPER(TRIM(nome_municipio)) = 'SENHOR DO BONFIM';
UPDATE territorios_municipios SET populacao = 65532 WHERE UPPER(TRIM(nome_municipio)) = 'CANDEIAS';
UPDATE territorios_municipios SET populacao = 53110 WHERE UPPER(TRIM(nome_municipio)) = 'DIAS D''ÁVILA';
UPDATE territorios_municipios SET populacao = 19807 WHERE UPPER(TRIM(nome_municipio)) = 'ITAPARICA';
UPDATE territorios_municipios SET populacao = 160968 WHERE UPPER(TRIM(nome_municipio)) = 'LAURO DE FREITAS';
UPDATE territorios_municipios SET populacao = 17211 WHERE UPPER(TRIM(nome_municipio)) = 'MADRE DE DEUS';
UPDATE territorios_municipios SET populacao = 43412 WHERE UPPER(TRIM(nome_municipio)) = 'MATA DE SÃO JOÃO';
UPDATE territorios_municipios SET populacao = 29373 WHERE UPPER(TRIM(nome_municipio)) = 'POJUCA';
UPDATE territorios_municipios SET populacao = 1969757 WHERE UPPER(TRIM(nome_municipio)) = 'SALVADOR';
UPDATE territorios_municipios SET populacao = 34543 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO FRANCISCO DO CONDE';
UPDATE territorios_municipios SET populacao = 34153 WHERE UPPER(TRIM(nome_municipio)) = 'SÃO SEBASTIÃO DO PASSÉ';
UPDATE territorios_municipios SET populacao = 88728 WHERE UPPER(TRIM(nome_municipio)) = 'SIMÕES FILHO';
UPDATE territorios_municipios SET populacao = 36330 WHERE UPPER(TRIM(nome_municipio)) = 'VERA CRUZ';

-- ============================================
-- Atualizar populacao_estimada dos territórios
-- (somar municípios)
-- ============================================
UPDATE territorios 
SET populacao_estimada = (
  SELECT COALESCE(SUM(populacao), 0) 
  FROM territorios_municipios 
  WHERE territorios_municipios.territorio_id = territorios.id
);
